### ISSUE TITLE
Dice verses Die

### ISSUE THREAD

**Issue by mrmichaelgallen** [Jeremiahsvaren/30-projects-in-30-days#7]
Hi Jeremiah,

I love the rolling of the die. Danny Condon pointed out that dice is the plural. Since you only one die, its roll die. Here is a link to [grammarist](http://grammarist.com/usage/dice-die/) that explains the difference. So Danny recommends changing it to Die or add another Die, so you have the plural. 

Best regards,

Michael

**Comment by Jeremiahsvaren** [comment]
Ahhh good catch. I'll be sure to fix that. Thanks!

**Comment by Jeremiahsvaren** [comment]
Fixed!
Thanks for letting me know!
